apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fiap.fullname" . }}
  labels:
    {{- include "fiap.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fiap.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "fiap.selectorLabels" . | nindent 8 }}
        {{- if .Values.datadog.enabled }}
        tags.datadoghq.com/service: {{ include "fiap.datadogService" . | quote }}
        tags.datadoghq.com/env: {{ .Values.datadog.env | quote }}
        tags.datadoghq.com/version: {{ .Values.datadog.version | quote }}
        admission.datadoghq.com/enabled: "true"
        {{- end }}
      annotations:
        {{- if .Values.datadog.enabled }}
        admission.datadoghq.com/js-lib.version: "latest"
        {{- end }}
    spec:
      serviceAccountName: {{ include "fiap.fullname" . }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ include "fiap.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: http
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
          {{- end }}
          env:
            - name: PORT
              value: "{{ .Values.containerPort }}"
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.envFromSecrets }}
          envFrom:
            {{- range .Values.envFromSecrets }}
            - secretRef:
                name: {{ .name }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
