apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fiap.fullname" . }}
  labels:
    {{- include "fiap.labels" . | nindent 4 }}
  {{- if .Values.irsaRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsaRoleArn | quote }}
  {{- end }}
